language: go
go:
- 1.4.1
after_success:
- go get -x github.com/laher/goxc
- goxc -bc "linux,amd64 darwin,amd64" -d "${TRAVIS_BUILD_DIR}/build"
addons:
  artifacts:
    key: bogus
    secret: bogus
    bucket: meatballhat-packer-build-onlinelabs
